parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\EventSubscriber\UserPasswordSubscriber:
        tags:
            - { name: 'doctrine.event_subscriber', connection: 'default' }
